version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: enter-container-name
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: enter-username
      MONGO_INITDB_ROOT_PASSWORD: enter-password
    volumes:
      - ./mongodb-data/:/data/db/
